config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri:  "http://backend.minikube.local/guestbook"
service:
  type: "ClusterIP"
  port: 80
replicCount: 1
image:
  repository: "phico/frontend"
  tag: "2.0"
ingress:
  host: "frontend.minikube.local"